--- a/Makefile
+++ b/Makefile
@@ -20,3 +20,8 @@
 
 start_all:
 	cd lucida/commandcenter && make start_server && sleep 5 && cd ../speechrecognition/kaldi_gstreamer_asr && make start_server && cd ../../imagematching/opencv_imm && make start_server && cd ../../questionanswering/OpenEphyra && make start_server && cd ../../calendar && make start_server
+
+default:
+	#used by Debian
+	cd lucida && make
+
