apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: qa
  name: qa-controller
spec:
  replicas: 1
  selector:
    name: qa
  template:
    metadata:
      labels:
        name: qa
    spec:
      containers:
      - image: claritylab/lucida:v2.0
        command: ['/bin/sh', '-c']
        args: ['cd $LUCIDAROOT/questionanswering/OpenEphyra/ && export wiki_indri_index=/usr/local/lucida/lucida/questionanswering/OpenEphyra/db/wiki_indri_index && ./start_server.sh']
        name: qa
        ports:
        - containerPort: 8083
          name: thrift
        volumeMounts:
          - mountPath: /usr/local/lucida/lucida/questionanswering/OpenEphyra/db
            name: openephyra-persistent-storage
            readOnly: false
      volumes:
        - hostPath:
            # Modify the path below.
            path: /home/lucida_data/openephyra # Store wiki_indri_index here if Wikipedia is downloaded.
          name: openephyra-persistent-storage
