Document: lucida
Title: Debian lucida Manual
Author: <insert document author here>
Abstract: This manual describes what lucida is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lucida/lucida.sgml.gz

Format: postscript
Files: /usr/share/doc/lucida/lucida.ps.gz

Format: text
Files: /usr/share/doc/lucida/lucida.text.gz

Format: HTML
Index: /usr/share/doc/lucida/html/index.html
Files: /usr/share/doc/lucida/html/*.html
